[package]
name = "core"
description = "Core business logic library for Notification Service"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "core"
path = "src/lib.rs"

[dependencies]
beep-server = { git = "https://github.com/beep-industries/crates" }
beep-auth = { git = "https://github.com/beep-industries/crates" }
chrono = { version = "0.4.42", features = ["serde"] }
serde = "1.0.228"
uuid = { version = "1.18.1", features = ["serde", "v7"] }
thiserror = "2.0.17"
serde_json = "1.0.145"
sqlx = { version = "0.8.6", features = ["chrono", "postgres", "runtime-tokio", "uuid"] }
axum = "0.8.7"
validator = "0.20.0"
tracing = "0.1.43"
lapin = "3.7.2"
tokio = "1.48.0"
futures-util = "0.3.31"
